version: '3.8'

services:
  converter:
    build: .
    container_name: rosbags_converter
    restart: "no"
    volumes:
      # Host yolunu aynen bağlıyoruz
      - /media/mehmet/Elements/bag:/ros_ws/data
    tty: true
    stdin_open: true
