services:
  kaist2bag:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros1-kaist2bag
    container_name: kaist2bag
    privileged: true
    network_mode: "host"
    volumes:
      - /media/mehmet/Elements/urban39:/dataset:ro
      - /media/mehmet/Elements/bag:/output
    stdin_open: true
    tty: true

