version: "3.9"

services:
  kaist2bag:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros1-kaist2bag
    container_name: kaist2bag
    privileged: true
    network_mode: "host"
    volumes:
      - /home/mehmet/urban39-pankyo:/data
    stdin_open: true
    tty: true

